# Generated by Django 5.1.1 on 2024-10-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
