# Generated by Django 5.1.1 on 2024-10-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_product_in_stock_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
